---
title: "NC Timecourse RNA-Seq: Visualizations"
output: html_notebook
---

# Step 4: Visualizations

From our analysis, we want to highlight dynamic transcription factors.
Let's first start with reading in the data from prev. analysis.

```{r}
library(dplyr)
library(pheatmap)

DESeq_1_files = list.files(path="./Exports/", pattern="*_AllGenes.csv", full.names=TRUE)
Annotated_Rlog_Positive_Averages <- read.csv("~/local_git/NC_Timecourse/RNA-Seq/Exports/Annotated_Rlog_Positive_Averages.csv", row.names=1, stringsAsFactors=FALSE)
rownames(Annotated_Rlog_Positive_Averages) <- Annotated_Rlog_Positive_Averages$Chick_ENSEMBL

HH6 <- read.csv(DESeq_1_files[5], row.names = 1)
HH6$Chick_ENSEMBL = rownames(HH6)
HH8 <- read.csv(DESeq_1_files[6], row.names = 1)
HH8$Chick_ENSEMBL = rownames(HH8)
HH10 <- read.csv(DESeq_1_files[1], row.names = 1)
HH10$Chick_ENSEMBL = rownames(HH10)
HH12 <- read.csv(DESeq_1_files[2], row.names = 1)
HH12$Chick_ENSEMBL = rownames(HH12)
HH14 <- read.csv(DESeq_1_files[3], row.names = 1)
HH14$Chick_ENSEMBL = rownames(HH14)
HH16 <- read.csv(DESeq_1_files[4], row.names = 1)
HH16$Chick_ENSEMBL = rownames(HH16)

TF_HH6 <- HH6 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

TF_HH8 <- HH8 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

TF_HH10 <- HH10 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

TF_HH12 <- HH12 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

TF_HH14 <- HH14 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

TF_HH16 <- HH16 %>% dplyr::filter(log2FoldChange > 0.5 & padj < 0.05 & TF_Status == "Transcription Factor") %>%
  dplyr::select(Chick_ENSEMBL, log2FoldChange, padj)

All_Enriched_TFs <- c(as.character(TF_HH6$Chick_ENSEMBL), as.character(TF_HH8$Chick_ENSEMBL),
                           as.character(TF_HH10$Chick_ENSEMBL), as.character(TF_HH12$Chick_ENSEMBL),
                           as.character(TF_HH14$Chick_ENSEMBL), as.character(TF_HH16$Chick_ENSEMBL))

All_Enriched_TFs <- unique(All_Enriched_TFs)
```

## Enriched TF Heatmap
We find that a Z-score of Rlog normalized counts from DESeq2 looks best.
```{r}
#looking at normalized counts
mat <- Annotated_Rlog_Positive_Averages[All_Enriched_TFs,2:7]
rownames(mat) <- paste0(as.character(Annotated_Rlog_Positive_Averages[All_Enriched_TFs,8]), "_"
                        ,rownames(mat))
colorRampPalette(c("#C42126","#D4D2D1","#212CC4"))(20)

p1 <- pheatmap(mat, cluster_cols = F, scale = "row", show_rownames = T, cellwidth = 15,
               color = colorRampPalette(c("#212CC4","#FFFFFF","#C42126"))(250),
               filename = "./Exports/TF_Heatmap_Rlog_Counts.pdf", width = 6, height = 8)
```

